config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  
  resources :users
  resources :ads, only: [:new, :create]
  resources :sessions, only: [:new, :create] do 
    collection do 
      delete "sign_out", to: "sessions#destroy", as: "sign_out" 
    end
  end
  
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  EMAIL_ADDRESS = /\A[^@\s]+@[^@\s]+\z/
  has_secure_password
  validates :name,  presence: true
  validates :email, format: { with: EMAIL_ADDRESS }, uniqueness: true

  has_many :ads
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :require_logged_user
  def new 
    @ad = Ad.new
  end

  def create
    @ad = current_user.ads.build(ad_params)
    if @ad.save 
      redirect_to root_path, notice: 'Ad was successfully created'
    else
      render :new
    end
  end

  private 
  def ad_params 
    params.require(:ad).permit(:title, :description, :price)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :user_signed_in?, :current_user
  
  def user_signed_in? 
    current_user.present?
  end

  def current_user 
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def require_logged_user 
    redirect_to new_session_path, alert: "You must be logged in" unless user_signed_in?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController 
  def index 
    @ads = Ad.all
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new 
    @user = User.new
  end

  def create 
    user = User.find_by(email: params[:user][:email])
    if user && user.authenticate(params[:user][:password])
      reset_session 
      session[:user_id]  = user.id
      redirect_to root_path, notice: t(".welcome", name: user.name)
    else 
      redirect_to new_session_path, alert: t(".invalid_credentials")
    end
  end

  def destroy
    reset_session
    redirect_to new_session_path, notice: t(".session_finished")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new  
   @user = User.new
  end 

  def create 
    @user = User.new(user_params) 
    if @user.save 
      NotificationMailer.welcome(@user.name, @user.email).deliver_later
      redirect_to new_session_path, notice: t(".success") 
    else
      render :new
    end
  end

  private 
  def user_params 
    params.require(:user).permit(:name, :password, :password_confirmation, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ads/new.html.erb
<div class="card">
  <div class="p-1 p-sm-4">
    <div class="d-flex justify-content-center align-items-center pb-2 mb-4">
              <%= form_with model: @ad do |form| %>
              <div>
                <%= form.label :title, class: 'form-label' %>
                <%= form.text_field :title , class:" form-control"%>
              </div>
              <div>
                <%= form.label :price, class: 'form-label' %>
                <%= form.text_field :price, class:" form-control" %>
              </div>
              <div>
                <%= form.label :description, class: 'form-label' %>
                <%= form.text_area :description, class:" form-control" %>
              </div>
              <div>
                
                <%= form.submit "Cadastrar", class: "btn btn-primary"%>
              </div>
              <% end %>
            </div>
          </div>
        </div>

app/views/home/index.html.erb
<h1>Anúncios</h1>
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Título </th>
      <th scope="col">Descrição </th>
      <th scope="col">Preço</th>
      <th scope="col">Criado em</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @ads.each do |ad| %>
    <tr>
      <td><%= ad.id %></td>
      <td><%= ad.title %></td>
      <td><%= ad.description %></td>
      <td><%= ad.price %></td>
      <td><%= ad.created_at.strftime('%d/%m/%Y %H:%M:%S') %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
      <li class="nav-item <%= current_page?(root_path)? "active" : "" %>">
        <%= link_to("Home", root_path, class: "nav-link") %>
      </li>
      <li class="nav-item <%= current_page?(ads_path)? "active" : "" %>">
        <%= link_to("Anuncios", new_ad_path, class: "nav-link") %>
      </li>
      
    </ul>
    <div class="nav-item d-flex">
      <ul class="navbar-nav">
        <li class="nav-item">
          <div class="py-2 mr-4" style="color:#fff;"><%= current_user.email %> </div>
        </li>
        <li class="nav-item">
          <%= link_to "Sair", sign_out_sessions_path, method: :delete, class: "nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to t("menu.signup"), new_user_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to t("menu.signin"), new_session_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Classificados</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    
    <div class="container">
    <%= render "layouts/admin/header" %>
    <p>
      <%= flash.notice %>
      <%= flash.alert %>
    </p>

    <%= yield %>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/new.html.erb
<div style="height: 150%!important;background-image: url('<%= image_path('login_bg2.jpeg') %>'); background-size: cover">
<div class="offset-4 col-4 authentication-inner py-5">
  <div class="card">
    <div class="p-4 p-sm-5">
      <div class="d-flex justify-content-center align-items-center pb-2 mb-4">
        <%= image_tag('logo', style: 'height: 90px;') %>
        </div>
            <% if @user.errors.any? %>
              <p><%= t("title.error")%></p>

              <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            <% end %>
            <br/>
            <%= form_for @user, url: "/users" do |form| %>
              <div class="form-group">
              <%= form.label :name, class: 'form-label' %>
              <%= form.text_field :name, class:" form-control" %>
            </div>

              <div class="form-group">
              <%= form.label :email, class: 'form-label' %>
              <%= form.email_field :email, class:" form-control" %>
            </div>

              <div class="form-group">
              <%= form.label :password, class: 'form-label' %>
              <%= form.password_field :password, class:" form-control" %>
            </div>

              <div class="form-group">
              <%= form.label :password_confirmation, class: 'form-label' %>
              <%= form.password_field :password_confirmation, class:" form-control" %>
            </div>
            <div class="d-flex justify-content-center align-items-center m-0">
              <%= form.submit 'Cadastrar', class: "btn btn-primary" %>
            </div>
              
            <% end %>
          </div>
        </div>
      </div>
    </div>
  